# Generated by Django 4.2.6 on 2023-10-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Salon',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
