# Generated by Django 4.2.6 on 2023-10-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0001_initial'),
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='category',
            field=models.ManyToManyField(to='categorys.category'),
        ),
    ]
