# Generated by Django 4.2.6 on 2023-10-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_salon_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='category',
        ),
    ]
