# Generated by Django 4.2.6 on 2023-10-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('salons', '0003_remove_salon_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='images',
            field=models.ManyToManyField(to='images.image'),
        ),
    ]
