# Generated by Django 4.2.6 on 2023-10-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_salon_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='isSpecial',
            field=models.BooleanField(default=False),
        ),
    ]
