# Generated by Django 4.2.6 on 2023-11-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0005_salon_isspecial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='Latitude',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salon',
            name='Longitude',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
