# Generated by Django 4.2.6 on 2023-11-17 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0006_salon_latitude_salon_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salon',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='salon',
            old_name='Longitude',
            new_name='longitude',
        ),
    ]
