# Generated by Django 4.2.6 on 2023-11-04 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_person_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='image',
        ),
    ]
